//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTour.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_vi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_vi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DTour.Client.Localization.SharedResource.vi", typeof(SharedResource_vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ khách hàng 24/7.
        /// </summary>
        internal static string _24_7_Customer_service {
            get {
                return ResourceManager.GetString("24/7 Customer service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 bước nữa để bắt đầu chuyến đi của bạn.
        /// </summary>
        internal static string _3_steps_away_from_your_trip {
            get {
                return ResourceManager.GetString("3 steps away from your trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.8 sao | 10000+ Đánh giá.
        /// </summary>
        internal static string _4_8_Stars___10000__Reviews {
            get {
                return ResourceManager.GetString("4.8 Stars | 10000+ Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về chúng tôi.
        /// </summary>
        internal static string About_Us {
            get {
                return ResourceManager.GetString("About Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string Add_new {
            get {
                return ResourceManager.GetString("Add new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quán trị.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người lớn.
        /// </summary>
        internal static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người lớn.
        /// </summary>
        internal static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuổi.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy bay.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ sân bay.
        /// </summary>
        internal static string Ancillary {
            get {
                return ResourceManager.GetString("Ancillary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền được chấp nhận.
        /// </summary>
        internal static string Approve_Amount {
            get {
                return ResourceManager.GetString("Approve Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phê duyệt nạp tiền.
        /// </summary>
        internal static string Approve_Top_up {
            get {
                return ResourceManager.GetString("Approve Top-up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấp thuận.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc bạn muốn thay đổi thông tin vé.
        /// </summary>
        internal static string Are_you_sure_you_want_to_update_the_outbound_ticket_ {
            get {
                return ResourceManager.GetString("Are you sure you want to update the outbound ticket?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đông Nam Á.
        /// </summary>
        internal static string Asia {
            get {
                return ResourceManager.GetString("Asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        internal static string Bank_Name {
            get {
                return ResourceManager.GetString("Bank Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản ngân hàng.
        /// </summary>
        internal static string Bank_No {
            get {
                return ResourceManager.GetString("Bank No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đặt chỗ.
        /// </summary>
        internal static string Booking_code {
            get {
                return ResourceManager.GetString("Booking code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt chỗ hoàn thành.
        /// </summary>
        internal static string Booking_Is_Successfully {
            get {
                return ResourceManager.GetString("Booking Is Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiêu đặt chỗ.
        /// </summary>
        internal static string Booking_Type {
            get {
                return ResourceManager.GetString("Booking Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua vé.
        /// </summary>
        internal static string Buy_Tickets {
            get {
                return ResourceManager.GetString("Buy Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người mua.
        /// </summary>
        internal static string Buyer_Information {
            get {
                return ResourceManager.GetString("Buyer Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển dụng.
        /// </summary>
        internal static string Careers {
            get {
                return ResourceManager.GetString("Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền mặt.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu.
        /// </summary>
        internal static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rẻ nhất.
        /// </summary>
        internal static string Cheapest {
            get {
                return ResourceManager.GetString("Cheapest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trẻ em.
        /// </summary>
        internal static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trẻ em/Thanh thiếu niên.
        /// </summary>
        internal static string Children_Youths {
            get {
                return ResourceManager.GetString("Children/Youths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung Quốc.
        /// </summary>
        internal static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn giá và hạng vé.
        /// </summary>
        internal static string Choose_Class_and_Fare {
            get {
                return ResourceManager.GetString("Choose Class and Fare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thành phố trong tay.
        /// </summary>
        internal static string cities_in_your_hand {
            get {
                return ResourceManager.GetString("cities in your hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa hết người dùng.
        /// </summary>
        internal static string Clear_Users {
            get {
                return ResourceManager.GetString("Clear Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toa.
        /// </summary>
        internal static string Coach {
            get {
                return ResourceManager.GetString("Coach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoa hồng.
        /// </summary>
        internal static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người liên hệ.
        /// </summary>
        internal static string Contact_Personal {
            get {
                return ResourceManager.GetString("Contact Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ chúng tôi.
        /// </summary>
        internal static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản quyền.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới tài khoản.
        /// </summary>
        internal static string Create_a_new_account {
            get {
                return ResourceManager.GetString("Create a new account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền tệ.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tổng hợp.
        /// </summary>
        internal static string Dash_board {
            get {
                return ResourceManager.GetString("Dash board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kính gửi.
        /// </summary>
        internal static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa vai trò.
        /// </summary>
        internal static string Delete_Role {
            get {
                return ResourceManager.GetString("Delete Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian khởi hành.
        /// </summary>
        internal static string Departure_time {
            get {
                return ResourceManager.GetString("Departure time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt cọc.
        /// </summary>
        internal static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đến.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tàu không dừng.
        /// </summary>
        internal static string Direct_train {
            get {
                return ResourceManager.GetString("Direct train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực hiện.
        /// </summary>
        internal static string Do_it {
            get {
                return ResourceManager.GetString("Do it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải về.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy vé thông qua mã đặt chỗ.
        /// </summary>
        internal static string Download_Tickets_by_Booking_code {
            get {
                return ResourceManager.GetString("Download Tickets by Booking code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức của DTour.
        /// </summary>
        internal static string DTour_News {
            get {
                return ResourceManager.GetString("DTour News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thời gian.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa vai trò.
        /// </summary>
        internal static string Edit_Role {
            get {
                return ResourceManager.GetString("Edit Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa vé.
        /// </summary>
        internal static string Edit_Ticket {
            get {
                return ResourceManager.GetString("Edit Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        internal static string Email_Address {
            get {
                return ResourceManager.GetString("Email Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ giá ngoại tệ.
        /// </summary>
        internal static string Exchange_rate {
            get {
                return ResourceManager.GetString("Exchange rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn giá vé, hạng dịch vụ.
        /// </summary>
        internal static string Fare__Class_Selection {
            get {
                return ResourceManager.GetString("Fare, Class Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhanh nhất.
        /// </summary>
        internal static string Fastest {
            get {
                return ResourceManager.GetString("Fastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm vé.
        /// </summary>
        internal static string Find_tickets {
            get {
                return ResourceManager.GetString("Find tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        internal static string Forgot_your_password {
            get {
                return ResourceManager.GetString("Forgot your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn phí hướng thành phố.
        /// </summary>
        internal static string Free_Virtual_City_Guide {
            get {
                return ResourceManager.GetString("Free Virtual City Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ: Thành phố, sân bay, nhà ga.
        /// </summary>
        internal static string From__City__Airport__Station {
            get {
                return ResourceManager.GetString("From: City, Airport, Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string Full_Name {
            get {
                return ResourceManager.GetString("Full Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện ảnh.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu.
        /// </summary>
        internal static string Get_Data {
            get {
                return ResourceManager.GetString("Get Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string Get_In_Touch {
            get {
                return ResourceManager.GetString("Get In Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về trang chủ.
        /// </summary>
        internal static string Go_Home {
            get {
                return ResourceManager.GetString("Go Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hà nội.
        /// </summary>
        internal static string Ha_Noi {
            get {
                return ResourceManager.GetString("Ha Noi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp chúng tôi.
        /// </summary>
        internal static string Help_us_help_ {
            get {
                return ResourceManager.GetString("Help us help!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đây là thông tin đặt chỗ chi tiết. Chúng tôi xin cảm ơn bạn đã mua dịch vụ của chúng tôi..
        /// </summary>
        internal static string Here_are_your_booking_details__We_thank_you_for_your_purchase_ {
            get {
                return ResourceManager.GetString("Here are your booking details. We thank you for your purchase.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ Chí Minh.
        /// </summary>
        internal static string Ho_Chi_Minh {
            get {
                return ResourceManager.GetString("Ho Chi Minh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong nước ban, ngô ngữ, múi giờ.
        /// </summary>
        internal static string In_your_country__language__time_zone {
            get {
                return ResourceManager.GetString("In your country, language, time zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khứ hồi.
        /// </summary>
        internal static string Inbound {
            get {
                return ResourceManager.GetString("Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn độ - Nepal.
        /// </summary>
        internal static string India_Nepal {
            get {
                return ResourceManager.GetString("India Nepal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng quốc tế như.
        /// </summary>
        internal static string International_format__like {
            get {
                return ResourceManager.GetString("International format, like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt cọc không?.
        /// </summary>
        internal static string Is_Deposit {
            get {
                return ResourceManager.GetString("Is Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật bản.
        /// </summary>
        internal static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàn quốc.
        /// </summary>
        internal static string Korea {
            get {
                return ResourceManager.GetString("Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        internal static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đại lý.
        /// </summary>
        internal static string List_of_Agent {
            get {
                return ResourceManager.GetString("List of Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hoa hồng.
        /// </summary>
        internal static string List_of_Commission {
            get {
                return ResourceManager.GetString("List of Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tiền tệ.
        /// </summary>
        internal static string List_of_Currency {
            get {
                return ResourceManager.GetString("List of Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tỉ giá.
        /// </summary>
        internal static string List_of_Exchange_Rate {
            get {
                return ResourceManager.GetString("List of Exchange Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách yêu cầu phê duyệt.
        /// </summary>
        internal static string List_of_Request_Top_up {
            get {
                return ResourceManager.GetString("List of Request Top-up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách quyền.
        /// </summary>
        internal static string List_of_Roles {
            get {
                return ResourceManager.GetString("List of Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nạp tiền.
        /// </summary>
        internal static string List_of_Top_up {
            get {
                return ResourceManager.GetString("List of Top-up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có tàu giữa hai trạm.
        /// </summary>
        internal static string No_train_found_between_these_two_stations {
            get {
                return ResourceManager.GetString("No train found between these two stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không dừng.
        /// </summary>
        internal static string Non_stop {
            get {
                return ResourceManager.GetString("Non-stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy. Xin hãy thử lại lần nữa.
        /// </summary>
        internal static string Not_found__Please_try_again {
            get {
                return ResourceManager.GetString("Not found. Please try again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        internal static string Old_Password {
            get {
                return ResourceManager.GetString("Old Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một chiều.
        /// </summary>
        internal static string One_Way {
            get {
                return ResourceManager.GetString("One Way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều hành khai thác.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều hành bởi.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chọn.
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty chúng tôi.
        /// </summary>
        internal static string Our_Company {
            get {
                return ResourceManager.GetString("Our Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ của chúng tôi.
        /// </summary>
        internal static string Our_Service {
            get {
                return ResourceManager.GetString("Our Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một chiều.
        /// </summary>
        internal static string OUT {
            get {
                return ResourceManager.GetString("OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một chiều.
        /// </summary>
        internal static string Outbound {
            get {
                return ResourceManager.GetString("Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách.
        /// </summary>
        internal static string Passenger {
            get {
                return ResourceManager.GetString("Passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hành khách.
        /// </summary>
        internal static string Passenger_Details {
            get {
                return ResourceManager.GetString("Passenger Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hành khách.
        /// </summary>
        internal static string Passenger_Information {
            get {
                return ResourceManager.GetString("Passenger Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách.
        /// </summary>
        internal static string Passengers {
            get {
                return ResourceManager.GetString("Passengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hành khách.
        /// </summary>
        internal static string Pax_s_Name {
            get {
                return ResourceManager.GetString("Pax\'s Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán thẻ.
        /// </summary>
        internal static string Pay_with_Card {
            get {
                return ResourceManager.GetString("Pay with Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán tiền mặt.
        /// </summary>
        internal static string Pay_with_Cash {
            get {
                return ResourceManager.GetString("Pay with Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu thanh toaán.
        /// </summary>
        internal static string Payment_Type {
            get {
                return ResourceManager.GetString("Payment Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần trăm.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string Phone_number {
            get {
                return ResourceManager.GetString("Phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu mới.
        /// </summary>
        internal static string Please_enter_your_password {
            get {
                return ResourceManager.GetString("Please enter your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn vé từ danh sách.
        /// </summary>
        internal static string Please_select_a_ticket_from_the_list {
            get {
                return ResourceManager.GetString("Please select a ticket from the list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin lựa chọn chuyến khác hoặc ngày khác.
        /// </summary>
        internal static string Please_select_other_stations_or_dates {
            get {
                return ResourceManager.GetString("Please select other stations or dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuẩn bị.
        /// </summary>
        internal static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết nhanh.
        /// </summary>
        internal static string Quick_Links {
            get {
                return ResourceManager.GetString("Quick Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ giá.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký mới.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị từ chối.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghỉ nhớ tôi.
        /// </summary>
        internal static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ vai trò.
        /// </summary>
        internal static string Remove_Role_on_User {
            get {
                return ResourceManager.GetString("Remove Role on User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu phê duyệt.
        /// </summary>
        internal static string Request_Approved {
            get {
                return ResourceManager.GetString("Request Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khôi phục.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khôi phục mật khẩu.
        /// </summary>
        internal static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm vai trò.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khứ hồi.
        /// </summary>
        internal static string Round_Trip {
            get {
                return ResourceManager.GetString("Round Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chặng.
        /// </summary>
        internal static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thay đổi.
        /// </summary>
        internal static string Save_Change {
            get {
                return ResourceManager.GetString("Save Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghế.
        /// </summary>
        internal static string Seat {
            get {
                return ResourceManager.GetString("Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem hành trình.
        /// </summary>
        internal static string See_itinerary_details {
            get {
                return ResourceManager.GetString("See itinerary details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn chuyến đi từ danh sách.
        /// </summary>
        internal static string Select_an_option_from_the_list {
            get {
                return ResourceManager.GetString("Select an option from the list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn vé khứ hồi.
        /// </summary>
        internal static string Select_Inbound {
            get {
                return ResourceManager.GetString("Select Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn vé một chiều.
        /// </summary>
        internal static string Select_Outbound {
            get {
                return ResourceManager.GetString("Select Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn giá vé của bạn.
        /// </summary>
        internal static string Select_your_Fare {
            get {
                return ResourceManager.GetString("Select your Fare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chọn.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gán vai trò.
        /// </summary>
        internal static string Set_Rights {
            get {
                return ResourceManager.GetString("Set Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gán vai trò.
        /// </summary>
        internal static string Set_Role_for_User {
            get {
                return ResourceManager.GetString("Set Role for User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ký kết.
        /// </summary>
        internal static string Sign_Date {
            get {
                return ResourceManager.GetString("Sign Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string Sign_out {
            get {
                return ResourceManager.GetString("Sign out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh.
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê đặt chỗ.
        /// </summary>
        internal static string Statistics_Booking {
            get {
                return ResourceManager.GetString("Statistics Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê dịch vụ.
        /// </summary>
        internal static string Statistics_Service {
            get {
                return ResourceManager.GetString("Statistics Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bước 1/2.
        /// </summary>
        internal static string Step_1_of_2 {
            get {
                return ResourceManager.GetString("Step 1 of 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bước 2/2.
        /// </summary>
        internal static string Step_2_of_2 {
            get {
                return ResourceManager.GetString("Step 2 of 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to điểm dừng.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển đổi.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế, phí.
        /// </summary>
        internal static string Tax_and_fees {
            get {
                return ResourceManager.GetString("Tax and fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khoản dịch vụ.
        /// </summary>
        internal static string Terms_of_Service {
            get {
                return ResourceManager.GetString("Terms of Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn.
        /// </summary>
        internal static string Thank_you {
            get {
                return ResourceManager.GetString("Thank you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các trường thông tin bắt buộc.
        /// </summary>
        internal static string These_fields_are_required {
            get {
                return ResourceManager.GetString("These fields are required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé.
        /// </summary>
        internal static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều kiện vé, hạng vé.
        /// </summary>
        internal static string Ticket__Fare_Conditions {
            get {
                return ResourceManager.GetString("Ticket, Fare Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều kiện vé.
        /// </summary>
        internal static string Ticket_Conditions {
            get {
                return ResourceManager.GetString("Ticket Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chọn vé.
        /// </summary>
        internal static string Ticket_Options {
            get {
                return ResourceManager.GetString("Ticket Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu vé.
        /// </summary>
        internal static string Ticket_Type {
            get {
                return ResourceManager.GetString("Ticket Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé.
        /// </summary>
        internal static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến: Thành phố, sân bay, nhà ga.
        /// </summary>
        internal static string To__City__Airport__Station {
            get {
                return ResourceManager.GetString("To: City, Airport, Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền.
        /// </summary>
        internal static string Top_up {
            get {
                return ResourceManager.GetString("Top-up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        internal static string Total_Amount {
            get {
                return ResourceManager.GetString("Total Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng đặt chỗ.
        /// </summary>
        internal static string Total_Booking {
            get {
                return ResourceManager.GetString("Total Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hủy chỗ.
        /// </summary>
        internal static string Total_Cancel {
            get {
                return ResourceManager.GetString("Total Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du lịch.
        /// </summary>
        internal static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du lịch theo yêu cầu.
        /// </summary>
        internal static string Tour_By_Requested {
            get {
                return ResourceManager.GetString("Tour By Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tàu.
        /// </summary>
        internal static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tàu số.
        /// </summary>
        internal static string Train_number {
            get {
                return ResourceManager.GetString("Train number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo giao dịch.
        /// </summary>
        internal static string Transaction_Reports {
            get {
                return ResourceManager.GetString("Transaction Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái giao dịch.
        /// </summary>
        internal static string Transaction_Status {
            get {
                return ResourceManager.GetString("Transaction Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số.
        /// </summary>
        internal static string Transport_No {
            get {
                return ResourceManager.GetString("Transport No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cẩm nang du lịch.
        /// </summary>
        internal static string Travel_Guide {
            get {
                return ResourceManager.GetString("Travel Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chi nhánh.
        /// </summary>
        internal static string Update_Station {
            get {
                return ResourceManager.GetString("Update Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu có độ dài tối thiểu 8 ký tự bao gồm chữ, số, ký tự đặc biệt.
        /// </summary>
        internal static string Use_8_or_more_characters_with_a_mix_of_letters__numbers__symbols {
            get {
                return ResourceManager.GetString("Use 8 or more characters with a mix of letters, numbers, symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng tài khoản cá nhân để đăng nhập.
        /// </summary>
        internal static string Use_a_local_account_to_log_in {
            get {
                return ResourceManager.GetString("Use a local account to log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng thông tin người mua.
        /// </summary>
        internal static string Use_Contact_Details {
            get {
                return ResourceManager.GetString("Use Contact Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sử dụng.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người SD có vai trò.
        /// </summary>
        internal static string User_have_role {
            get {
                return ResourceManager.GetString("User have role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quán lý người dùng.
        /// </summary>
        internal static string User_Management {
            get {
                return ResourceManager.GetString("User Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sử dụng.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem báo cáo.
        /// </summary>
        internal static string View_Report {
            get {
                return ResourceManager.GetString("View Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem NSD có vai trò.
        /// </summary>
        internal static string View_Roles_on_User {
            get {
                return ResourceManager.GetString("View Roles on User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem người dùng.
        /// </summary>
        internal static string View_Users {
            get {
                return ResourceManager.GetString("View Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi chấp thuận.
        /// </summary>
        internal static string We_Accept {
            get {
                return ResourceManager.GetString("We Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạng vé.
        /// </summary>
        internal static string Your_class {
            get {
                return ResourceManager.GetString("Your class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé của bạn.
        /// </summary>
        internal static string Your_Tickets {
            get {
                return ResourceManager.GetString("Your Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé của bạn cứu thế giới.
        /// </summary>
        internal static string Your_Tickets_Save_the_World {
            get {
                return ResourceManager.GetString("Your Tickets Save the World", resourceCulture);
            }
        }
    }
}
